package com.ppio.data.bill.mysql.mapper;

import com.ppio.data.bill.mysql.entity.TDwsDcacheDockerMonitor;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TDwsDcacheDockerMonitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dws_dcache_docker_monitor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dws_dcache_docker_monitor
     *
     * @mbg.generated
     */
    int insert(TDwsDcacheDockerMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dws_dcache_docker_monitor
     *
     * @mbg.generated
     */
    int insertSelective(TDwsDcacheDockerMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dws_dcache_docker_monitor
     *
     * @mbg.generated
     */
    TDwsDcacheDockerMonitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dws_dcache_docker_monitor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDwsDcacheDockerMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dws_dcache_docker_monitor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDwsDcacheDockerMonitor record);

    List<String> selectMachines(@Param("dt") int dt);

    List<TDwsDcacheDockerMonitor> selectByMachineId(@Param("dt") int dt, @Param("mid") String mid);
}