package com.ppio.data.bill.mysql.entity;

import lombok.Data;
import lombok.ToString;

@Data
@ToString
public class TDwsDcacheDockerMonitor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dws_dcache_docker_monitor.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dws_dcache_docker_monitor.machine_id
     *
     * @mbg.generated
     */
    private String machineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dws_dcache_docker_monitor.time_id
     *
     * @mbg.generated
     */
    private String timeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dws_dcache_docker_monitor.time
     *
     * @mbg.generated
     */
    private Long time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dws_dcache_docker_monitor.custom_id
     *
     * @mbg.generated
     */
    private String customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dws_dcache_docker_monitor.bw_upload
     *
     * @mbg.generated
     */
    private Long bwUpload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dws_dcache_docker_monitor.dt
     *
     * @mbg.generated
     */
    private String dt;

    private long bsBwUpload ;
}